version: '3'

services:
  bitcoin-jvm:
    image: renatohvo/bitcoin-quarkus-jvm:latest
    build:
      context: ./
      dockerfile: src/main/docker/Dockerfile.${QUARKUS_MODE:-jvm}
    environment:
      QUARKUS_DATASOURCE_URL: jdbc:mysql://mysql-bitcoin:3306/bitcoin?autoReconnect=true
    networks:
      - mysql-db
    ports:
      - 8080:8080
    depends_on:
      - mysql-bitcoin

  mysql-bitcoin:
    image: renatohvo/mysql-quarkus-db:8.0.34
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
    volumes:
      - mysql.bitcoin:/var/lib/mysql
    ports:
      - 3307:3306
    networks:
      - mysql-db

  prometheus:
    image: prom/prometheus:v2.26.0
    container_name: prometheus
    ports:
      - 9090:9090
    networks:
      - mysql-db
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command: --config.file=/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    ports:
      - 3000:3000
    networks:
      - mysql-db
    depends_on:
      - prometheus

networks:
 mysql-db:
  driver: bridge

volumes:
  mysql.bitcoin: